version: '3'

services:
  authserver:
    image: pepperdash/pepperdash.serverapps.authserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Migrations__Enabled=true
      - Migrations__Provider=PostgreSql
      - ConnectionStrings__PostgreSqlProvider=Host=postgres;Database=PepperDash.Connect.AuthServer.PostgreSql.Dev;Username=postgres;Password=P3pp3rD4sh!;
    ports:
      - "5001:80"
    restart: always
  postgres:
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'P3pp3rD4sh!'
      POSTGRES_DB: 'PepperDash.Connect.AuthServer.PostgreSql'
    restart: always

networks:
 default:
  external:
   name: pdt_fog_network