version: '3.2'

services:
  portainer_agent:
    image: portainer/agent:latest
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.portainer_agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
      CAP_HOST_MANAGEMENT: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer:latest
    command: 
     - -H tcp://tasks.portainer_agent:9001 
     - --tlsskipverify 
     - --templates https://portal-dev.devcloud.pepperdash.com/__pdapps-static/apptemplates.json
     - --logo https://portal-dev.devcloud.pepperdash.com/__pdapps-static/PD-Fog-Logo.png
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
#       - "traefik.frontend.rule=Host:${HOSTNAME}"
       - "traefik.frontend.rule=PathPrefixStrip:/portainer"
       - "traefik.backend=portainer"
       - "traefik.port=9000"
       #- "traefik.weight=10"
       - "traefik.enable=true"
       - "traefik.passHostHeader=true"
       - "traefik.docker.network=pdt_fog_network"
       - "traefik.frontend.entryPoints=http"
       #- "traefik.backend.loadbalancer.swarm=true"
       #- "traefik.backend.loadbalancer.method=drr"
       # https://github.com/containous/traefik/issues/563#issuecomment-421360934
       - "traefik.frontend.redirect.regex=^(.*)/portainer$$"
       - "traefik.frontend.redirect.replacement=$$1/portainer/"
       - "traefik.frontend.rule=PathPrefix:/portainer;ReplacePathRegex: ^/portainer/(.*) /$$1"
      
networks:
 default:
  external:
   name: pdt_fog_network

volumes:
  portainer_data:
