version: '3.3'
services:
  reverse-proxy:
    image: traefik:latest
    command: --api --docker --docker.swarmMode --docker.domain=pepperdash.net --docker.watch
    ports:
     - 80:80
     - 8080:8080
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - pdt_fog_network
    logging:
      driver: json-file
  whoami:
    image: containous/whoami:latest
    networks:
     - pdt_fog_network
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.frontend.rule: Host:bosd-photon02.pepperdash.net,bosd-photon02;Path:/whoami
        traefik.port: '80'
networks:
  pdt_fog_network:
    external: true
